/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.web;

import com.google.inject.Guice;
import com.google.inject.Injector;
import com.google.inject.Provider;
import com.google.inject.util.Modules;
import java.util.concurrent.ExecutorService;
import org.xtext.example.mydsl.MyDslRuntimeModule;
import org.xtext.example.mydsl.MyDslStandaloneSetup;

/**
 * Initialization support for running Xtext languages in web applications.
 */
public class MyDslWebSetup extends MyDslStandaloneSetup {
	
	private final Provider<ExecutorService> executorServiceProvider;
	
	MyDslWebSetup(Provider<ExecutorService> executorServiceProvider) {
		this.executorServiceProvider = executorServiceProvider;
	}
	
	@Override
	public Injector createInjector() {
		MyDslRuntimeModule runtimeModule = new MyDslRuntimeModule();
		MyDslWebModule webModule = new MyDslWebModule(executorServiceProvider);
		return Guice.createInjector(Modules.override(runtimeModule).with(webModule));
	}
	
}
