/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.web;

import com.google.inject.Provider;
import java.util.concurrent.ExecutorService;

/**
 * Use this class to register additional components to be used within the web application.
 */
public class MyDslWebModule extends AbstractMyDslWebModule {

	public MyDslWebModule(Provider<ExecutorService> executorServiceProvider) {
		super(executorServiceProvider);
	}
}
